title: Stormchaser RPG
description: The official source for the Stormchaser RPG.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: Stormchaser-Logo.png
aux_links:
  "Stormchaser Roleplaying":
    - "https://stormchaserroleplaying.com"
